export const GIVEN_OFFERS_REQUEST = "GIVEN_OFFERS_REQUEST";
export const GIVEN_OFFERS_SUCCESS = "GIVEN_OFFERS_SUCCESS";
export const GIVEN_OFFERS_FAILURE = "GIVEN_OFFERS_FAILURE";

export const RECEIVED_OFFERS_REQUEST = "RECEIVED_OFFERS_REQUEST";
export const RECEIVED_OFFERS_SUCCESS = "RECEIVED_OFFERS_SUCCESS";
export const RECEIVED_OFFERS_FAILURE = "RECEIVED_OFFERS_FAILURE";

export const REJECT_OFFER_REQUEST = "REJECT_OFFER_REQUEST";
export const REJECT_OFFER_SUCCESS = "REJECT_OFFER_SUCCESS";
export const REJECT_OFFER_FAILURE = "REJECT_OFFER_FAILURE";

export const ACCEPT_OFFER_REQUEST = "ACCEPT_OFFER_REQUEST";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAILURE = "ACCEPT_OFFER_FAILURE";

export const CANCEL_OFFER_REQUEST = "CANCEL_OFFER_REQUEST";
export const CANCEL_OFFER_SUCCESS = "CANCEL_OFFER_SUCCESS";
export const CANCEL_OFFER_FAILURE = "CANCEL_OFFER_FAILURE";
