export const ALL_BRANDS_REQUEST = "ALL_BRANDS_REQUEST";
export const ALL_BRANDS_SUCCESS = "ALL_BRANDS_SUCCESS";
export const ALL_BRANDS_FAILURE = "ALL_BRANDS_FAILURE";

export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_FAILURE = "BRAND_FAILURE";
