export const ALL_COLORS_REQUEST = "ALL_COLORS_REQUEST";
export const ALL_COLORS_SUCCESS = "ALL_COLORS_SUCCESS";
export const ALL_COLORS_FAILURE = "ALL_COLORS_FAILURE";

export const COLOR_REQUEST = "COLOR_REQUEST";
export const COLOR_SUCCESS = "COLOR_SUCCESS";
export const COLOR_FAILURE = "COLOR_FAILURE";
