export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAILURE = "ALL_PRODUCTS_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const OFFER_PRODUCT_REQUEST = "OFFER_PRODUCT_REQUEST";
export const OFFER_PRODUCT_SUCCESS = "OFFER_PRODUCT_SUCCESS";
export const OFFER_PRODUCT_FAILURE = "OFFER_PRODUCT_FAILURE";

export const PURCHASE_PRODUCT_REQUEST = "PURCHASE_PRODUCT_REQUEST";
export const PURCHASE_PRODUCT_SUCCESS = "PURCHASE_PRODUCT_SUCCESS";
export const PURCHASE_PRODUCT_FAILURE = "PURCHASE_PRODUCT_FAILURE";
