export const ALL_STATUS_REQUEST = "ALL_STATUS_REQUEST";
export const ALL_STATUS_SUCCESS = "ALL_STATUS_SUCCESS";
export const ALL_STATUS_FAILURE = "ALL_STATUS_FAILURE";

export const STATUS_REQUEST = "STATUS_REQUEST";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
export const STATUS_FAILURE = "STATUS_FAILURE";
